### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/tutorials#47]
- [x] General Travis architecture
- [x] Tutorial: How to set up Travis for a new repo
	- [x] Encrypting slack key
	- [x] Adding ROS key
	- [x] Repo notification key

**Comment by Olavhaasie** [comment]
Adding `ROS_KEY` variable is no longer necessary.
What is meant by _Repo notification key_?

**Comment by Ishadijcks** [comment]
Nice!

It's the key that allows Travis to publish notifications in Slack
