### ISSUE TITLE
Add documentation on how to add rosbag node to launch file

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/tutorials#54]
https://project-march.github.io/tutorials/doc/using_the_march_iv/log_files.html

Seems to be missing a crucial part: how to add rosbag node to march_iv.launch

**Comment by Ishadijcks** [comment]
Recording a bag is located under the ros tools section, as it is not strictly related to our exoskeleton

https://project-march.github.io/tutorials/doc/useful_ros_tools/ros_bag.html#ros-bag-label
