### ISSUE TITLE
Creating march_ws is incomplete

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/tutorials#90]
Documentation needs to be added on the installation of the following packages:

**Comment by Olavhaasie** [comment]
sudo apt-get install ros-kinetic-ros-control ros-kinetic-ros-controllers ros-kinetic-effort-controllers ros-kinetic-joint-state-controller ros-kinetic-joint-trajectory-controller

I think this needs to be added. And restarting Ubuntu after this worked for me

**Comment by Ishadijcks** [comment]
Can you add an extra step to the documentation?
