### ISSUE TITLE
Build script exception running Sphinx

### ISSUE THREAD

**Issue by Olavhaasie** [project-march/tutorials#91]
I followed the [tutorial](https://project-march.github.io/tutorials/doc/development/documentation.html) for building the tutorials locally, but I get an error when running the `sphinx-build` step in `./build_locally.sh`.

```
Running Sphinx v2.2.0
Adding copy buttons to code blocks...

Exception occurred:
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/olav/march_ws/src/march_tutorials/_scripts/tutorialformatter.py", line 121
    print 'tutorialformatter.py error: sub-tutorial %s not found.' % sub_name
                                                                 ^
SyntaxError: Missing parentheses in call to 'print'
The full traceback has been saved in /tmp/sphinx-err-tjtxlh4y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

It seems that it uses python3, which needs parentheses, but it should be using python2. Any idea on how to fix this?

**Comment by Ishadijcks** [comment]
Interesting, the `tutorialformatter.py` is not used at the moment. It's probably a local problem, but we can also remove the script for now.

**Comment by Olavhaasie** [comment]
Apparently Sphinx cannot be installed in python2 and python3 concurrently, so I had to remove sphinx from python3 so it would use python2

    pip3 uninstall sphinx

**Comment by Ishadijcks** [comment]
Did that fix the issue, can you add a `.. note::` directive to the page?
